export const capabilities: string[] = [
	"E-Commerce",
	"Dropshipping Website",
	"Personal Portfolio",
	"Real-Estate Portfolio",
	"UI/UX Design (Figma)",
	"Car Agent/Agency Portfolio",
	"Visa Agent/Agency Portfolio",
	"Content Management System (CMS)",
	"Agency Website",
	"Landing Page",
	"Website Development (Frontend Only)",
	"Website Development (Serverless Full-Stack)",
	"API Integration",
	"Booking website (Airline)",
	"Booking website (Hotel & Reservations)",
	"Schorlarship Website",
	"Airline Website",
	"Computer Base Test (CBT) Web App",
	"Mobile Development",
];
