interface Project {
	title: string;
	thumbnailUrls: string[];
	previewUrl: string;
	tags: string[];
	githubUrl: string;
}

export const projects: Project[] = [
	{
		title: `Al-Qibla International Travel & Tours LTD.`,
		thumbnailUrls: ["alqibla-1.png"],
		previewUrl: "https://www.alqibla-intl-travels.com/",
		tags: [
			"Svelte",
			"SvelteKit",
			"TypeScript",
			"ShadCN-Svelte",
			"Tailwind CSS",
			"Zod",
			"Vite",
		],
		githubUrl: "https://github.com/Officialibn1/al-qibla.git",
	},
	{
		title: `Blog 99 & Blog Custom CMS`,
		thumbnailUrls: ["blog99-1.png"],
		previewUrl: "https://blog99-gold.vercel.app/",
		tags: [
			"Svelte",
			"Sveltekit",
			"TypeScript",
			"ShadCN-Svelte",
			"Tailwind CSS",
			"Zod",
			"Vite",
			"MongoDB",
			"Mongoose",
			"NodeJS",
			"JWT",
			"Vercel",
		],
		githubUrl: "https://github.com/Officialibn1/blog99.git",
	},
	{
		title: `SG Real Estate Website`,
		thumbnailUrls: ["SG Estate.png"],
		previewUrl: "https://sg-real-estate.vercel.app/",
		tags: [
			"Svelte",
			"Sveltekit",
			"JavaScript",
			"Tailwind CSS",
			"Zod",
			"Vite",
			"Vercel",
		],
		githubUrl: "https://github.com/Officialibn1/sg_real_estate.git",
	},
	{
		title: `Client Management System (CMS)`,
		thumbnailUrls: ["CM System-1.png"],
		previewUrl: "https://client-management-system-sigma.vercel.app/",
		tags: [
			"React",
			"TypeScript",
			"ShadCN",
			"Tailwind CSS",
			"Zod",
			"Vite",
			"GraphQL",
			"Apollo Client",
			"Hasura",
			"PostgreSQL",
			"NodeJS",
			"JWT",
			"Vercel",
			"Firebase",
			"Firebase-Auth",
		],
		githubUrl: "https://github.com/Officialibn1/client-management-system",
	},
	{
		title: `Top Wears Store (E-Commerce)`,
		thumbnailUrls: ["Top Wears Light.png"],
		previewUrl: "https://topwears-store.vercel.app/",
		tags: [
			"React",
			"NextJS",
			"TypeScript",
			"ShadCN",
			"Tailwind CSS",
			"GraphQL",
			"Sanity CMS",
			"Aceternity UI",
			"Vercel",
			"Stripe",
		],
		githubUrl: "https://github.com/Officialibn1/topwears_store",
	},
	{
		title: `99 Wears (E-Commerce)`,
		thumbnailUrls: ["99 Stores.png"],
		previewUrl: "https://ninety9store.vercel.app/",
		tags: [
			"React",
			"TypeScript",
			"ShadCN",
			"Tailwind CSS",
			"GraphQL",
			"Sanity CMS",
			"Aceternity UI",
			"Vercel",
			"Stripe",
			"Strapi CMS",
			"PostgreSQL",
			"Hasura",
			"Apollo Client",
		],
		githubUrl: "https://github.com/Officialibn1/99store",
	},
	{
		title: `Seaco (Coffee Company)`,
		thumbnailUrls: ["Seaco.png"],
		previewUrl: "https://seaco.vercel.app/",
		tags: ["React", "NextJS", "TypeScript", "ShadCN", "Tailwind CSS", "Vercel"],
		githubUrl: "https://github.com/Officialibn1/Seaco",
	},
];
